accent = "#4db6ac"
active_border_color = "#4db6ac"
active_tab_background = "#4db6ac"

cursor = "#c0caf5"
foreground = "#a9b1d6"
background = "#1c1f26"
selection_foreground = "#1c1f26"
selection_background = "#4db6ac"

color0 = "#32344a"
color1 = "#f7768e"
color2 = "#9ece6a"
color3 = "#e0af68"
color4 = "#4db6ac"
color5 = "#ad8ee6"
color6 = "#449dab"
color7 = "#787c99"
color8 = "#444b6a"
color9 = "#ff7a93"
color10 = "#b9f27c"
color11 = "#ff9e64"
color12 = "#26a69a"
color13 = "#bb9af7"
color14 = "#4db6ac"
color15 = "#acb0d0"
